on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm start
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_target: ~/