on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and start
        run: |
          npm install
          npm run build
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
              curl -o-  https://raw.githubusercontent.com/creationix/nvm/v@.33.8/install.sh | bash
              . ~/.nvm/nvm.sh

               nvm install 14
               npm install -g pm2
               cd ~/CRAWLING
               git pull origin master
               npm install
               npm run build
               pm2 restart crawling
