on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm install
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
              curl -o-  https://raw.githubusercontent.com/creationix/nvm/v@.33.8/install.sh | bash
              . ~/.nvm/nvm.sh

               nvm install 14
               npm install -g pm2
               cd ~/CRAWLING
               git pull origin master
               npm install
               npm start
               pm2 restart crawling
